### ISSUE TITLE
SDCC command lines for correct Build ?

### ISSUE THREAD

**Issue by gh-jmg** [fenrir-naru/gpib-usbcdc#2]
Hi.
  This looks cool, as we are looking for CDC examples using SiLabs C8051F380.

However, I'm unsure about the build settings, and make barfs on this PC.
 Q:  What is the expected code image size & .MEM file ? (It might pay to upload a .HEX and .MAP & .MEM files to github, so users can see what they should get ?)

I can get a manual build if I use this command line 
\SDCC\bin\sdcc.exe --debug --stack-auto --nooverlay --model-small --use-stdout --opt-code-speed -c gpib.c -o OutSDCC\
but that --stack-auto seems to pass **everything** on the stack, and gives a large  size: 19059
with .MEM showing DATA space is all Stack. 
However, that's likely to be VERY slow.

If I try a simpler 
\SDCC\bin\sdcc.exe --debug --use-stdout --opt-code-speed -c gpib.c -o OutSDCC\
(I find I need --nooverlay removed, as otherwise it cannot all fit in DATA)

that compiles all modules fine, & gives a much better looking MEM report, & better Size : 16835  **except** for gpib.c which fails with error reports like this 

gpib.c:66: error 92: Functions called via pointers must be 'reentrant' to take this many (bytes for) arguments
gpib.c:67: error 92: Functions called via pointers must be 'reentrant' to take this many (bytes for) arguments
gpib.c:68: error 92: Functions called via pointers must be 'reentrant' to take this many (bytes for) arguments
gpib.c:74: error 92: Functions called via pointers must be 'reentrant' to take this many (bytes for) arguments
gpib.c:78: error 92: Functions called via pointers must be 'reentrant' to take this many (bytes for) arguments
gpib.c:82: error 92: Functions called via pointers must be 'reentrant' to take this many (bytes for) arguments
gpib.c:94: error 92: Functions called via pointers must be 'reentrant' to take this many (bytes for) arguments
gpib.c:101: error 92: Functions called via pointers must be 'reentrant' to take this many (bytes for) arguments
gpib.c:118: error 92: Functions called via pointers must be 'reentrant' to take this many (bytes for) arguments
gpib.c:410: error 92: Functions called via pointers must be 'reentrant' to take this many (bytes for) arguments
gpib.c:413: error 92: Functions called via pointers must be 'reentrant' to take this many (bytes for) arguments
gpib.c:421: error 92: Functions called via pointers must be 'reentrant' to take this many (bytes for) arguments
gpib.c:426: error 92: Functions called via pointers must be 'reentrant' to take this many (bytes for) arguments
gpib.c:575: error 92: Functions called via pointers must be 'reentrant' to take this many (bytes for) arguments

and I could not get a SDCC  __reentrant  keyword to apply in the function declarations, as they seem tangled in #defines etc 
These seem simple print routines ?
Do you have a gpib.c version that has  __reentrant applied (or gpib.c that does not need reentrant?), or do you have any command line tips, for getting a build that completes ok ?

**Comment by fenrir-naru** [comment]
@gh-jmg Which version of SDCC do you use? The recommended version is 3.3.0 (too old compared to the latest 3.9.0). The build setting is written in [Makefile](https://github.com/fenrir-naru/gpib-usbcdc/blob/1eadc10dd73dfb62c7bd8b7165bf292fc622c347/firmware/Makefile#L35).

**Comment by fenrir-naru** [comment]
@gh-jmg If you have further information, please let me know. I will close this issue due to no reply.
