### ISSUE TITLE
Popping up as GPIB-USB comport

### ISSUE THREAD

**Issue by Stefanhg** [fenrir-naru/gpib-usbcdc#3]
Hello.

Is this device supposed to pop up as a GPIB-USB comport?
if so, i'd guess it doesn't support Pyvisa with multiple instruments or does it?

**Comment by fenrir-naru** [comment]
Hi, thank you for your comment.
I do not know PyVISA well at this time. The function of GPIB-USBCDC is just a bridge between USB COM port and GPIB, which may mean you can control it from PyVISA if you can write a driver to wrap its commands for PyVISA.
(edited) I hope that pyvisa/pyvisa#112 may be helpful.

**Comment by Stefanhg** [comment]
If anyone else was confused about this i made a Library today that can use the prologix. It is as simple as the Pyvisa driver
https://github.com/Decee1/GPIBprologix
