### ISSUE TITLE
Correct firmware for C8051F387

### ISSUE THREAD

**Issue by feroxib** [fenrir-naru/gpib-usbcdc#4]
Hello,
I wanted to ask if there is a firmware version for the adapter if you're using a C8051F387 
You recommended either the  EFM8UB20F32G-A-QFN32 or C8051F387.
But im having problems with Windows detecting the adapter correctly.
Do i have to build my own firmware or is there a premade one?

Thank you for your help

**Comment by fenrir-naru** [comment]
@feroxib Thank you for your comment.
I think there is no significant difference between the two devices, but I am not sure.
I will attach [C8051F38x datasheet](https://github.com/fenrir-naru/gpib-usbcdc/files/7035788/C8051F38x.pdf) I locally downloaded, please check it.
