### ISSUE TITLE
Documentation: Add Warning about GPIB Address 0 

### ISSUE THREAD

**Issue by biergaizi** [fenrir-naru/gpib-usbcdc#5]
I spent days trying to get this GPIB converter to work on my voltmeter but I couldn't even after checking the documentation many times. The voltmeter did not not respond to any command. Meanwhile, strangely, a National Instruments converter (clone) worked without any problem. Eventually I had to troubleshoot this problem by probing the GPIB bus painstalkingly with a logic analyzer. The conclusion was almost hilarious: the voltmeter's GPIB address was set to 0, which is ambiguous, and I didn't realize it.

After I changed the address, it worked flawlessly.

This is not a bug since address 0 is reserved. But I suggest updating the documentation with a warning on GPIB device address 0, so other newcomers don't have to fall into the same trap.

## Debugging

If the controller set the device as a listener first and set itself as a talker, it creates a bus contention - both the controller and the device have address 0 and both think they should start talking now, trashing the bus, so it doesn't work. This is the behavior of gpib-usbcdc.

![905778031e0c48ea](https://github.com/fenrir-naru/gpib-usbcdc/assets/1310693/b1d4d67d-81a9-4758-95a8-32c96ce402e1)

But... If the controller set itself as a talker first before set the device as a listener, it works (in a mysterious way if you don't have a logic analyzer), because there's only one active talker at this point. Apparently National Instruments does this, perhaps as a workaround just for this case. So it worked without any problem.

![fe96947d7244152c](https://github.com/fenrir-naru/gpib-usbcdc/assets/1310693/a33744d2-b748-4c17-8236-7e68d077df10)

**Comment by fenrir-naru** [comment]
@biergaizi Thank you so much. I added some text to Readme based on your report.
